"""
AI 编译器工具链 - 代码生成器（C/Python）
"""

from __future__ import annotations

from typing import Optional, Any

from src.frontend.ast import (
    ASTNode, ASTVisitor,
    IntegerLiteral, FloatLiteral, StringLiteral, BooleanLiteral, NullLiteral,
    Identifier, BinaryOp, UnaryOp, Assignment, Call, Access,
    ArrayLiteral, RecordLiteral, LambdaExpr, TernaryExpr, CastExpr,
    TypeAnnotation, ArrayType, TensorType, FunctionType,
    Parameter, VariableDecl, Block, IfStmt, WhileStmt, ForStmt, ForInStmt,
    BreakStmt, ContinueStmt, ReturnStmt, AssertStmt, DeferStmt, MatchStmt,
    ExpressionStmt, FunctionDecl, ClassDecl, ImportDecl, ExportDecl,
    TypeDecl, Module, Program, MatchPattern,
    TypeInfo, TypeKind,
    INT_TYPE, FLOAT_TYPE, BOOL_TYPE, STRING_TYPE, VOID_TYPE,
)
from src.middle.ir import (
    IRModule, IRFunction, IRInstruction, IRValue, IRValueType, BasicBlock, IROpcode, IRGlobal,
)
from src.utils.errors import CodeGenError, ErrorReporter


class CCodeGenerator(ASTVisitor):
    """C 代码生成器"""

    def __init__(self, error_reporter: Optional[ErrorReporter] = None):
        self.error_reporter: ErrorReporter = error_reporter or ErrorReporter()
        self._output: list[str] = []
        self._indent_level: int = 0
        self._indent_size: int = 4
        self._function_name: str = ""
        self._in_function: bool = False
        self._var_counter: int = 0
        self._loop_counter: int = 0
        self._include_headers: set[str] = set()
        self._generated_code: str = ""

    def generate(self, program: Program) -> str:
        """生成 C 代码"""
        self._output = []
        self._indent_level = 0
        self._include_headers = {"stdio.h", "stdlib.h", "stdbool.h", "string.h"}

        # 输出头文件
        self._emit_line("// Generated by AI Compiler Toolchain")
        self._emit_line("// Target: C")
        self._emit_line("")
        self._emit_include_headers()
        self._emit_line("")

        # 生成代码
        for module in program.modules:
            for decl in module.declarations:
                self.visit(decl)

        self._generated_code = "\n".join(self._output)
        return self._generated_code

    def _emit_line(self, line: str = "") -> None:
        """输出一行"""
        if line:
            indent = " " * (self._indent_level * self._indent_size)
            self._output.append(f"{indent}{line}")
        else:
            self._output.append("")

    def _emit_include_headers(self) -> None:
        """输出头文件引用"""
        for header in sorted(self._include_headers):
            self._emit_line(f"#include <{header}>")

    def _type_to_c(self, type_node: Optional[ASTNode]) -> str:
        """将 AST 类型转换为 C 类型"""
        if type_node is None:
            return "int"
        if isinstance(type_node, TypeAnnotation):
            mapping = {
                "int": "int", "float": "double", "bool": "bool",
                "string": "char*", "void": "void", "array": "int*",
                "tensor": "double*", "record": "void*", "any": "void*",
            }
            return mapping.get(type_node.name, "int")
        if isinstance(type_node, ArrayType):
            elem_type = self._type_to_c(type_node.element_type)
            return f"{elem_type}*"
        if isinstance(type_node, TensorType):
            return "double*"
        if isinstance(type_node, FunctionType):
            return "void*"
        return "int"

    def type_info_to_c(self, type_info: TypeInfo) -> str:
        """将 TypeInfo 转换为 C 类型"""
        mapping = {
            TypeKind.INTEGER: "int",
            TypeKind.FLOAT: "double",
            TypeKind.BOOLEAN: "bool",
            TypeKind.STRING: "char*",
            TypeKind.VOID: "void",
            TypeKind.ARRAY: "int*",
            TypeKind.TENSOR: "double*",
        }
        return mapping.get(type_info.kind, "int")

    # ---------- 访问者 ----------

    def visit_Program(self, node: Program) -> Any:
        self._emit_line("int main(int argc, char* argv[]) {")
        self._indent_level += 1
        for module in node.modules:
            for decl in module.declarations:
                self.visit(decl)
        self._emit_line("return 0;")
        self._indent_level -= 1
        self._emit_line("}")

    def visit_Module(self, node: Module) -> Any:
        for decl in node.declarations:
            self.visit(decl)

    def visit_FunctionDecl(self, node: FunctionDecl) -> Any:
        old_func = self._function_name
        self._function_name = node.name

        ret_type = self._type_to_c(node.return_type) if node.return_type else "void"
        params = []
        for param in node.params:
            ptype = self._type_to_c(param.type_annotation) if param.type_annotation else "int"
            params.append(f"{ptype} {param.name}")

        self._emit_line(f"{ret_type} {node.name}({', '.join(params)}) {{")
        self._indent_level += 1
        self._in_function = True

        self.visit(node.body)

        if ret_type != "void" and node.body:
            # 确保有返回值
            pass

        self._indent_level -= 1
        self._emit_line("}")
        self._emit_line("")
        self._in_function = False
        self._function_name = old_func

    def visit_ClassDecl(self, node: ClassDecl) -> Any:
        self._emit_line(f"typedef struct {node.name} {{")
        self._indent_level += 1
        for member in node.body:
            if isinstance(member, VariableDecl):
                mtype = self._type_to_c(member.type_annotation)
                self._emit_line(f"{mtype} {member.name};")
        self._indent_level -= 1
        self._emit_line(f"}} {node.name};")
        self._emit_line("")

    def visit_VariableDecl(self, node: VariableDecl) -> Any:
        var_type = self._type_to_c(node.type_annotation) if node.type_annotation else "int"
        if node.initializer:
            if isinstance(node.initializer, IntegerLiteral):
                self._emit_line(f"{var_type} {node.name} = {node.initializer.value};")
            elif isinstance(node.initializer, FloatLiteral):
                self._emit_line(f"{var_type} {node.name} = {node.initializer.value};")
            elif isinstance(node.initializer, StringLiteral):
                self._emit_line(f"{var_type} {node.name} = \"{node.initializer.value}\";")
            elif isinstance(node.initializer, BooleanLiteral):
                val = "true" if node.initializer.value else "false"
                self._emit_line(f"{var_type} {node.name} = {val};")
            else:
                self._emit_line(f"{var_type} {node.name} = 0;")
        else:
            self._emit_line(f"{var_type} {node.name} = 0;")

    def visit_Block(self, node: Block) -> Any:
        for stmt in node.statements:
            self.visit(stmt)

    def visit_IfStmt(self, node: IfStmt) -> Any:
        cond = self._expr_to_c(node.condition)
        self._emit_line(f"if ({cond}) {{")
        self._indent_level += 1
        self.visit(node.then_body)
        self._indent_level -= 1

        if node.else_body:
            self._emit_line("} else {")
            self._indent_level += 1
            self.visit(node.else_body)
            self._indent_level -= 1

        self._emit_line("}")

    def visit_WhileStmt(self, node: WhileStmt) -> Any:
        cond = self._expr_to_c(node.condition)
        self._emit_line(f"while ({cond}) {{")
        self._indent_level += 1
        self.visit(node.body)
        self._indent_level -= 1
        self._emit_line("}")

    def visit_ForStmt(self, node: ForStmt) -> Any:
        init_str = ""
        if node.init:
            if isinstance(node.init, VariableDecl):
                init_str = self._type_to_c(node.init.type_annotation) + " " + node.init.name + " = 0"
            else:
                init_str = self._expr_to_c(node.init)

        cond_str = self._expr_to_c(node.condition) if node.condition else "1"
        update_str = self._expr_to_c(node.update) if node.update else ""

        self._emit_line(f"for ({init_str}; {cond_str}; {update_str}) {{")
        self._indent_level += 1
        self.visit(node.body)
        self._indent_level -= 1
        self._emit_line("}")

    def visit_ForInStmt(self, node: ForInStmt) -> Any:
        target = self._expr_to_c(node.target)
        iterable = self._expr_to_c(node.iterable)
        self._emit_line(f"for (int _i = 0; _i < {iterable}; _i++) {{")
        self._indent_level += 1
        self.visit(node.body)
        self._indent_level -= 1
        self._emit_line("}")

    def visit_BreakStmt(self, node: BreakStmt) -> Any:
        self._emit_line("break;")

    def visit_ContinueStmt(self, node: ContinueStmt) -> Any:
        self._emit_line("continue;")

    def visit_ReturnStmt(self, node: ReturnStmt) -> Any:
        if node.value:
            val = self._expr_to_c(node.value)
            self._emit_line(f"return {val};")
        else:
            self._emit_line("return;")

    def visit_AssertStmt(self, node: AssertStmt) -> Any:
        cond = self._expr_to_c(node.condition)
        if node.message:
            msg = self._expr_to_c(node.message)
            self._emit_line(f'if (!({cond})) {{ fprintf(stderr, "Assertion failed: %s\\n", {msg}); exit(1); }}')
        else:
            self._emit_line(f'if (!({cond})) {{ fprintf(stderr, "Assertion failed\\n"); exit(1); }}')

    def visit_DeferStmt(self, node: DeferStmt) -> Any:
        # 简化: defer 在 C 中不做特殊处理，直接执行调用
        self.visit(node.call)

    def visit_ExpressionStmt(self, node: ExpressionStmt) -> Any:
        expr = self._expr_to_c(node.expression)
        if expr:
            self._emit_line(f"{expr};")

    def visit_ImportDecl(self, node: ImportDecl) -> Any:
        pass

    def visit_ExportDecl(self, node: ExportDecl) -> Any:
        self.visit(node.declaration)

    def visit_TypeDecl(self, node: TypeDecl) -> Any:
        pass

    def _expr_to_c(self, node: Optional[ASTNode]) -> str:
        """将表达式 AST 转换为 C 代码字符串"""
        if node is None:
            return "0"
        if isinstance(node, IntegerLiteral):
            return str(node.value)
        if isinstance(node, FloatLiteral):
            return str(node.value)
        if isinstance(node, StringLiteral):
            escaped = node.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            return f'"{escaped}"'
        if isinstance(node, BooleanLiteral):
            return "true" if node.value else "false"
        if isinstance(node, NullLiteral):
            return "NULL"
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, BinaryOp):
            left = self._expr_to_c(node.left)
            right = self._expr_to_c(node.right)
            op_map = {
                "PLUS": "+", "MINUS": "-", "STAR": "*", "SLASH": "/",
                "PERCENT": "%", "EQUAL_EQUAL": "==", "NOT_EQUAL": "!=",
                "LESS": "<", "GREATER": ">", "LESS_EQUAL": "<=",
                "GREATER_EQUAL": ">=", "AND": "&&", "OR": "||",
                "BIT_AND": "&", "BIT_OR": "|", "BIT_XOR": "^",
                "LEFT_SHIFT": "<<", "RIGHT_SHIFT": ">>",
                "DOT": ".", "COMMA": ",",
            }
            op = op_map.get(node.op.type, node.op.type)
            return f"({left} {op} {right})"
        if isinstance(node, UnaryOp):
            operand = self._expr_to_c(node.operand)
            op_map = {"MINUS": "-", "NOT": "!", "BIT_NOT": "~", "PLUS_PLUS": "++", "MINUS_MINUS": "--"}
            op = op_map.get(node.op.type, node.op.type)
            if node.prefix:
                return f"{op}{operand}"
            else:
                return f"{operand}{op}"
        if isinstance(node, Assignment):
            target = self._expr_to_c(node.target)
            value = self._expr_to_c(node.value)
            op_map = {"EQUAL": "=", "PLUS_EQUAL": "+=", "MINUS_EQUAL": "-=",
                      "STAR_EQUAL": "*=", "SLASH_EQUAL": "/="}
            op = op_map.get(node.op.type, "=")
            return f"{target} {op} {value}"
        if isinstance(node, Call):
            callee = self._expr_to_c(node.callee)
            args = [self._expr_to_c(arg) for arg in node.args]
            return f"{callee}({', '.join(args)})"
        if isinstance(node, Access):
            obj = self._expr_to_c(node.obj)
            key = self._expr_to_c(node.key)
            if node.is_index:
                return f"{obj}[{key}]"
            return f"{obj}.{key}"
        if isinstance(node, ArrayLiteral):
            elems = [self._expr_to_c(e) for e in node.elements]
            return "{" + ", ".join(elems) + "}"
        if isinstance(node, TernaryExpr):
            cond = self._expr_to_c(node.condition)
            then_expr = self._expr_to_c(node.then_expr)
            else_expr = self._expr_to_c(node.else_expr)
            return f"({cond} ? {then_expr} : {else_expr})"
        if isinstance(node, CastExpr):
            target_type = self._type_to_c(node.target_type)
            expr = self._expr_to_c(node.expr)
            return f"({target_type})({expr})"
        if isinstance(node, LambdaExpr):
            return "NULL"  # 简化
        if isinstance(node, MatchStmt):
            return "0"
        return "0"

    def visit_TypeAnnotation(self, node: TypeAnnotation) -> Any:
        pass

    def visit_ArrayType(self, node: ArrayType) -> Any:
        pass

    def visit_TensorType(self, node: TensorType) -> Any:
        pass

    def visit_FunctionType(self, node: FunctionType) -> Any:
        pass

    def visit_Parameter(self, node: Parameter) -> Any:
        pass

    def visit_MatchStmt(self, node: MatchStmt) -> Any:
        self._emit_line("// match statement (unimplemented)")

    def visit_MatchPattern(self, node: MatchPattern) -> Any:
        pass


class PythonCodeGenerator(ASTVisitor):
    """Python 代码生成器"""

    def __init__(self, error_reporter: Optional[ErrorReporter] = None):
        self.error_reporter: ErrorReporter = error_reporter or ErrorReporter()
        self._output: list[str] = []
        self._indent_level: int = 0
        self._in_function: bool = False
        self._function_name: str = ""

    def generate(self, program: Program) -> str:
        """生成 Python 代码"""
        self._output = []
        self._indent_level = 0

        self._emit_line("# Generated by AI Compiler Toolchain")
        self._emit_line("# Target: Python")
        self._emit_line("")

        for module in program.modules:
            for decl in module.declarations:
                self.visit(decl)

        return "\n".join(self._output)

    def _emit_line(self, line: str = "") -> None:
        if line:
            indent = " " * (self._indent_level * 4)
            self._output.append(f"{indent}{line}")
        else:
            self._output.append("")

    def visit_Program(self, node: Program) -> Any:
        for module in node.modules:
            self.visit(module)

    def visit_Module(self, node: Module) -> Any:
        for decl in node.declarations:
            self.visit(decl)

    def visit_FunctionDecl(self, node: FunctionDecl) -> Any:
        old_func = self._function_name
        self._function_name = node.name

        params = []
        for param in node.params:
            params.append(param.name)

        self._emit_line(f"def {node.name}({', '.join(params)}):")
        self._indent_level += 1
        self._in_function = True

        if node.return_type:
            ret_type = self._type_to_python(node.return_type)
            if ret_type != "None":
                pass  # Python 类型注解可选

        self.visit(node.body)

        self._indent_level -= 1
        self._emit_line("")
        self._in_function = False
        self._function_name = old_func

    def _type_to_python(self, type_node: Optional[ASTNode]) -> str:
        if type_node is None:
            return "Any"
        if isinstance(type_node, TypeAnnotation):
            mapping = {
                "int": "int", "float": "float", "bool": "bool",
                "string": "str", "void": "None", "array": "list",
                "tensor": "list", "any": "Any",
            }
            return mapping.get(type_node.name, "Any")
        return "Any"

    def visit_ClassDecl(self, node: ClassDecl) -> Any:
        if node.base_class:
            base = self._expr_to_python(node.base_class)
            self._emit_line(f"class {node.name}({base}):")
        else:
            self._emit_line(f"class {node.name}:")
        self._indent_level += 1
        if node.body:
            for member in node.body:
                self.visit(member)
        else:
            self._emit_line("pass")
        self._indent_level -= 1
        self._emit_line("")

    def visit_VariableDecl(self, node: VariableDecl) -> Any:
        if node.initializer:
            init = self._expr_to_python(node.initializer)
            self._emit_line(f"{node.name} = {init}")
        else:
            var_type = self._type_to_python(node.type_annotation)
            self._emit_line(f"{node.name} = None  # type: {var_type}")

    def visit_Block(self, node: Block) -> Any:
        for stmt in node.statements:
            self.visit(stmt)

    def visit_IfStmt(self, node: IfStmt) -> Any:
        cond = self._expr_to_python(node.condition)
        self._emit_line(f"if {cond}:")
        self._indent_level += 1
        self.visit(node.then_body)
        self._indent_level -= 1

        if node.else_body:
            if isinstance(node.else_body, IfStmt):
                self._emit_line("elif:")
                self._indent_level += 1
                self.visit(node.else_body)
                self._indent_level -= 1
            else:
                self._emit_line("else:")
                self._indent_level += 1
                self.visit(node.else_body)
                self._indent_level -= 1

    def visit_WhileStmt(self, node: WhileStmt) -> Any:
        cond = self._expr_to_python(node.condition)
        self._emit_line(f"while {cond}:")
        self._indent_level += 1
        self.visit(node.body)
        self._indent_level -= 1

    def visit_ForStmt(self, node: ForStmt) -> Any:
        # Python for 循环使用 range
        if node.condition:
            cond = self._expr_to_python(node.condition)
            self._emit_line(f"while {cond}:")
            self._indent_level += 1
            self.visit(node.body)
            if node.update:
                update = self._expr_to_python(node.update)
                self._emit_line(update)
            self._indent_level -= 1
        else:
            self._emit_line("while True:")
            self._indent_level += 1
            self.visit(node.body)
            self._indent_level -= 1

    def visit_ForInStmt(self, node: ForInStmt) -> Any:
        target = self._expr_to_python(node.target)
        iterable = self._expr_to_python(node.iterable)
        self._emit_line(f"for {target} in {iterable}:")
        self._indent_level += 1
        self.visit(node.body)
        self._indent_level -= 1

    def visit_BreakStmt(self, node: BreakStmt) -> Any:
        self._emit_line("break")

    def visit_ContinueStmt(self, node: ContinueStmt) -> Any:
        self._emit_line("continue")

    def visit_ReturnStmt(self, node: ReturnStmt) -> Any:
        if node.value:
            val = self._expr_to_python(node.value)
            self._emit_line(f"return {val}")
        else:
            self._emit_line("return")

    def visit_AssertStmt(self, node: AssertStmt) -> Any:
        cond = self._expr_to_python(node.condition)
        if node.message:
            msg = self._expr_to_python(node.message)
            self._emit_line(f"assert {cond}, {msg}")
        else:
            self._emit_line(f"assert {cond}")

    def visit_ExpressionStmt(self, node: ExpressionStmt) -> Any:
        expr = self._expr_to_python(node.expression)
        self._emit_line(expr)

    def visit_ImportDecl(self, node: ImportDecl) -> Any:
        self._emit_line(f"import {node.module}")

    def visit_ExportDecl(self, node: ExportDecl) -> Any:
        self.visit(node.declaration)

    def visit_TypeDecl(self, node: TypeDecl) -> Any:
        self._emit_line(f"# type alias: {node.name}")

    def _expr_to_python(self, node: Optional[ASTNode]) -> str:
        if node is None:
            return "None"
        if isinstance(node, IntegerLiteral):
            return str(node.value)
        if isinstance(node, FloatLiteral):
            return str(node.value)
        if isinstance(node, StringLiteral):
            escaped = node.value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
            return f"'{escaped}'"
        if isinstance(node, BooleanLiteral):
            return "True" if node.value else "False"
        if isinstance(node, NullLiteral):
            return "None"
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, BinaryOp):
            left = self._expr_to_python(node.left)
            right = self._expr_to_python(node.right)
            op_map = {
                "PLUS": "+", "MINUS": "-", "STAR": "*", "SLASH": "/",
                "PERCENT": "%", "EQUAL_EQUAL": "==", "NOT_EQUAL": "!=",
                "LESS": "<", "GREATER": ">", "LESS_EQUAL": "<=",
                "GREATER_EQUAL": ">=", "AND": "and", "OR": "or",
                "BIT_AND": "&", "BIT_OR": "|", "BIT_XOR": "^",
                "LEFT_SHIFT": "<<", "RIGHT_SHIFT": ">>",
            }
            op = op_map.get(node.op.type, node.op.type)
            return f"({left} {op} {right})"
        if isinstance(node, UnaryOp):
            operand = self._expr_to_python(node.operand)
            op_map = {"MINUS": "-", "NOT": "not ", "BIT_NOT": "~", "PLUS_PLUS": "", "MINUS_MINUS": ""}
            op = op_map.get(node.op.type, node.op.type)
            if node.prefix:
                return f"{op}{operand}"
            return f"{operand}{op}"
        if isinstance(node, Assignment):
            target = self._expr_to_python(node.target)
            value = self._expr_to_python(node.value)
            op_map = {"EQUAL": "=", "PLUS_EQUAL": "+=", "MINUS_EQUAL": "-=",
                      "STAR_EQUAL": "*=", "SLASH_EQUAL": "/="}
            op = op_map.get(node.op.type, "=")
            return f"{target} {op} {value}"
        if isinstance(node, Call):
            callee = self._expr_to_python(node.callee)
            args = [self._expr_to_python(arg) for arg in node.args]
            return f"{callee}({', '.join(args)})"
        if isinstance(node, Access):
            obj = self._expr_to_python(node.obj)
            key = self._expr_to_python(node.key)
            if node.is_index:
                return f"{obj}[{key}]"
            return f"{obj}.{key}"
        if isinstance(node, ArrayLiteral):
            elems = [self._expr_to_python(e) for e in node.elements]
            return "[" + ", ".join(elems) + "]"
        if isinstance(node, TernaryExpr):
            cond = self._expr_to_python(node.condition)
            then_expr = self._expr_to_python(node.then_expr)
            else_expr = self._expr_to_python(node.else_expr)
            return f"({then_expr} if {cond} else {else_expr})"
        if isinstance(node, CastExpr):
            return self._expr_to_python(node.expr)
        return "None"

    def visit_TypeAnnotation(self, node: TypeAnnotation) -> Any:
        pass

    def visit_ArrayType(self, node: ArrayType) -> Any:
        pass

    def visit_TensorType(self, node: TensorType) -> Any:
        pass

    def visit_FunctionType(self, node: FunctionType) -> Any:
        pass

    def visit_Parameter(self, node: Parameter) -> Any:
        pass

    def visit_MatchStmt(self, node: MatchStmt) -> Any:
        self._emit_line("# match statement (unimplemented)")

    def visit_MatchPattern(self, node: MatchPattern) -> Any:
        pass

    def visit_DeferStmt(self, node: DeferStmt) -> Any:
        self.visit(node.call)


class CodeGenerator:
    """代码生成器工厂"""

    def __init__(self, error_reporter: Optional[ErrorReporter] = None):
        self.error_reporter = error_reporter or ErrorReporter()

    def generate(self, program: Program, target: str = "c") -> str:
        """生成目标代码"""
        if target == "c":
            gen = CCodeGenerator(self.error_reporter)
            return gen.generate(program)
        elif target == "python":
            gen = PythonCodeGenerator(self.error_reporter)
            return gen.generate(program)
        else:
            raise CodeGenError(f"不支持的目标语言: {target}")

    @staticmethod
    def generate_from_ir(ir_module: IRModule, target: str = "c") -> str:
        """从 IR 生成代码（简化实现）"""
        if target == "c":
            return CodeGenerator._ir_to_c(ir_module)
        elif target == "python":
            return CodeGenerator._ir_to_python(ir_module)
        else:
            raise CodeGenError(f"不支持的目标语言: {target}")

    @staticmethod
    def _type_to_c_str(vt: IRValueType) -> str:
        mapping = {
            IRValueType.VOID: "void", IRValueType.INT1: "int", IRValueType.INT8: "char",
            IRValueType.INT16: "short", IRValueType.INT32: "int", IRValueType.INT64: "long long",
            IRValueType.FLOAT32: "float", IRValueType.FLOAT64: "double",
            IRValueType.POINTER: "void*", IRValueType.ARRAY: "int*", IRValueType.TENSOR: "double*",
            IRValueType.STRING: "char*",
        }
        return mapping.get(vt, "int")

    @staticmethod
    def _ir_to_c(ir_module: IRModule) -> str:
        lines = ["// Generated from IR by AI Compiler Toolchain",
                 '#include <stdio.h>', '#include <stdlib.h>', '#include <stdbool.h>', '', '']
        for func_name, func in ir_module.functions.items():
            ret_type = CodeGenerator._type_to_c_str(func.return_type)
            params = []
            for p in func.params:
                params.append(f"{CodeGenerator._type_to_c_str(p.value_type)} {p.name.lstrip('%')}")
            lines.append(f"{ret_type} {func_name}({', '.join(params)}) {{")
            for block in func.blocks:
                lines.append(f"  {block.name}:")
                for instr in block.instructions:
                    if instr.opcode == IROpcode.LABEL:
                        continue
                    elif instr.opcode == IROpcode.RETURN:
                        if instr.operands:
                            lines.append(f"    return {instr.operands[0]};")
                        else:
                            lines.append(f"    return;")
                    elif instr.opcode == IROpcode.GOTO:
                        lines.append(f"    goto {instr.label};")
                    elif instr.opcode == IROpcode.IF_GOTO:
                        cond = instr.operands[0] if instr.operands else "0"
                        lines.append(f"    if (!{cond}) goto {instr.label};")
                    elif instr.opcode == IROpcode.CALL:
                        if instr.dest:
                            lines.append(f"    {instr.dest} = {instr.operands[0].name}(...);")
                        else:
                            fname = instr.operands[0].name if instr.operands else "unknown"
                            lines.append(f"    {fname}();")
                    elif instr.dest:
                        ops = ", ".join(str(op) for op in instr.operands)
                        lines.append(f"    {instr.dest} = {instr.opcode.name.lower()}({ops});")
            lines.append("}")
            lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _ir_to_python(ir_module: IRModule) -> str:
        lines = ["# Generated from IR by AI Compiler Toolchain", ""]
        for func_name, func in ir_module.functions.items():
            params = [p.name.lstrip('%') for p in func.params]
            lines.append(f"def {func_name}({', '.join(params)}):")
            for block in func.blocks:
                for instr in block.instructions:
                    if instr.opcode == IROpcode.LABEL:
                        lines.append(f"    # {block.name}")
                    elif instr.opcode == IROpcode.RETURN:
                        if instr.operands:
                            lines.append(f"    return {instr.operands[0]}")
                        else:
                            lines.append(f"    return")
                    elif instr.opcode == IROpcode.CALL:
                        fname = instr.operands[0].name if instr.operands else "unknown"
                        args = ", ".join(str(op) for op in instr.operands[1:])
                        if instr.dest:
                            lines.append(f"    {instr.dest} = {fname}({args})")
                        else:
                            lines.append(f"    {fname}({args})")
                    elif instr.dest:
                        ops = ", ".join(str(op) for op in instr.operands)
                        lines.append(f"    {instr.dest} = {instr.opcode.name.lower()}({ops})")
            lines.append("")
        return "\n".join(lines)