"""
AI 编译器工具链 - LLVM IR 生成器
"""

from __future__ import annotations

from typing import Optional, Any

from src.middle.ir import (
    IRModule, IRFunction, IRInstruction, IRValue, IRValueType, BasicBlock, IROpcode,
)
from src.utils.errors import CodeGenError, ErrorReporter


class LLVMIRGenerator:
    """LLVM IR 代码生成器"""

    def __init__(self, error_reporter: Optional[ErrorReporter] = None):
        self.error_reporter: ErrorReporter = error_reporter or ErrorReporter()
        self._output: list[str] = []
        self._temp_counter: int = 0
        self._label_counter: int = 0
        self._var_map: dict[str, str] = {}  # IR var -> LLVM var
        self._current_function: Optional[str] = None
        self._named_values: dict[str, str] = {}
        self._string_constants: list[tuple[str, str]] = []

    def generate(self, ir_module: IRModule) -> str:
        """从 IR 模块生成 LLVM IR"""
        self._output = []
        self._temp_counter = 0
        self._label_counter = 0
        self._var_map.clear()
        self._string_constants.clear()

        self._emit_line("; Generated by AI Compiler Toolchain")
        self._emit_line("; Target: LLVM IR")
        self._emit_line(f'; Module: {ir_module.name}')
        self._emit_line("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"")
        self._emit_line("target triple = \"x86_64-pc-linux-gnu\"")
        self._emit_line("")

        # 声明外部函数
        self._emit_line("declare i32 @printf(i8*, ...)")
        self._emit_line("declare void @exit(i32)")
        self._emit_line("declare i8* @malloc(i64)")
        self._emit_line("declare void @free(i8*)")
        self._emit_line("")

        # 字符串常量
        for name, value in self._string_constants:
            escaped = value.replace("\\", "\\5C").replace("\n", "\\0A").replace("\"", "\\22")
            self._emit_line(f"@{name} = private unnamed_addr constant [{len(value) + 1} x i8] c\"{escaped}\\00\"")
        if self._string_constants:
            self._emit_line("")

        # 生成全局变量
        for name, g in ir_module.globals.items():
            llvm_type = self._ir_type_to_llvm(g.value_type)
            if g.initializer is not None:
                self._emit_line(f"@{name} = global {llvm_type} {g.initializer}")
            else:
                self._emit_line(f"@{name} = global {llvm_type} zeroinitializer")
        if ir_module.globals:
            self._emit_line("")

        # 生成函数
        for func_name, func in ir_module.functions.items():
            self._generate_function(func)

        return "\n".join(self._output)

    def _ir_type_to_llvm(self, vt: IRValueType) -> str:
        """将 IR 类型转换为 LLVM 类型"""
        mapping = {
            IRValueType.VOID: "void",
            IRValueType.INT1: "i1",
            IRValueType.INT8: "i8",
            IRValueType.INT16: "i16",
            IRValueType.INT32: "i32",
            IRValueType.INT64: "i64",
            IRValueType.UINT8: "i8",
            IRValueType.UINT16: "i16",
            IRValueType.UINT32: "i32",
            IRValueType.UINT64: "i64",
            IRValueType.FLOAT32: "float",
            IRValueType.FLOAT64: "double",
            IRValueType.POINTER: "ptr",
            IRValueType.ARRAY: "ptr",
            IRValueType.TENSOR: "ptr",
            IRValueType.STRING: "i8*",
            IRValueType.FUNCTION: "ptr",
            IRValueType.STRUCT: "ptr",
        }
        return mapping.get(vt, "i32")

    def _new_temp(self) -> str:
        """创建新临时变量"""
        name = f"%{self._temp_counter}"
        self._temp_counter += 1
        return name

    def _new_label(self, prefix: str = "L") -> str:
        """创建新标签"""
        label = f"{prefix}{self._label_counter}"
        self._label_counter += 1
        return label

    def _generate_function(self, func: IRFunction) -> None:
        """生成 LLVM 函数"""
        self._current_function = func.name
        self._var_map.clear()
        self._named_values.clear()

        # 函数类型
        ret_type = self._ir_type_to_llvm(func.return_type)
        param_types = [self._ir_type_to_llvm(p.value_type) for p in func.params]
        param_str = ", ".join(param_types)

        # 函数声明
        if func.is_extern:
            self._emit_line(f"declare {ret_type} @{func.name}({param_str})")
            self._emit_line("")
            return

        # 函数参数
        params = []
        for i, p in enumerate(func.params):
            llvm_type = self._ir_type_to_llvm(p.value_type)
            params.append(f"{llvm_type} {p.name}")
            self._named_values[p.name] = p.name

        self._emit_line(f"define {ret_type} @{func.name}({', '.join(params)}) {{")
        self._indent_level = 1

        # 生成基本块
        for block in func.blocks:
            self._generate_block(block)

        self._emit_line("}")
        self._emit_line("")

    def _generate_block(self, block: BasicBlock) -> None:
        """生成基本块"""
        self._emit_line(f"{block.name}:")

        for instr in block.instructions:
            self._generate_instruction(instr)

    _indent_level: int = 0

    def _generate_instruction(self, instr: IRInstruction) -> None:
        """生成单条指令"""
        comment = f"  ; {instr.comment}" if instr.comment else ""

        if instr.opcode == IROpcode.LABEL:
            return  # 在基本块级别处理

        elif instr.opcode == IROpcode.RETURN or instr.opcode == IROpcode.RET:
            if instr.operands:
                op = instr.operands[0]
                val = self._get_operand_value(op)
                ret_type = self._ir_type_to_llvm(op.value_type)
                self._emit_line(f"  ret {ret_type} {val}{comment}")
            else:
                self._emit_line(f"  ret void{comment}")

        elif instr.opcode == IROpcode.GOTO:
            self._emit_line(f"  br label %{instr.label}{comment}")

        elif instr.opcode == IROpcode.IF_GOTO:
            cond = instr.operands[0] if instr.operands else None
            if cond:
                cond_val = self._get_operand_value(cond)
                # 转换为 i1 类型
                i1_val = self._new_temp()
                self._emit_line(f"  {i1_val} = icmp ne i32 {cond_val}, 0{comment}")
                # 需要目标标签和下一个标签
                target = instr.label
                next_label = self._new_label("if_false")
                self._emit_line(f"  br i1 {i1_val}, label %{target}, label %{next_label}{comment}")
                self._emit_line(f"{next_label}:")

        elif instr.opcode == IROpcode.CALL:
            func_name = instr.operands[0].name if instr.operands else ""
            func_name = func_name.lstrip("@")
            args = instr.operands[1:]
            arg_strs = []
            for arg in args:
                arg_type = self._ir_type_to_llvm(arg.value_type)
                arg_val = self._get_operand_value(arg)
                arg_strs.append(f"{arg_type} {arg_val}")

            ret_type = self._ir_type_to_llvm(instr.dest.value_type) if instr.dest else "void"
            if instr.dest:
                dest = self._allocate_temp(instr.dest)
                self._emit_line(f"  {dest} = call {ret_type} @{func_name}({', '.join(arg_strs)}){comment}")
            else:
                self._emit_line(f"  call {ret_type} @{func_name}({', '.join(arg_strs)}){comment}")

        elif instr.opcode == IROpcode.ALLOCA:
            if instr.dest:
                dest = self._allocate_temp(instr.dest)
                self._emit_line(f"  {dest} = alloca i32{comment}")

        elif instr.opcode == IROpcode.STORE:
            if len(instr.operands) >= 2:
                val = self._get_operand_value(instr.operands[1])
                ptr = self._get_operand_value(instr.operands[0])
                val_type = self._ir_type_to_llvm(instr.operands[1].value_type)
                self._emit_line(f"  store {val_type} {val}, ptr {ptr}{comment}")

        elif instr.opcode == IROpcode.LOAD:
            if instr.dest and instr.operands:
                ptr = self._get_operand_value(instr.operands[0])
                dest = self._allocate_temp(instr.dest)
                load_type = self._ir_type_to_llvm(instr.dest.value_type)
                self._emit_line(f"  {dest} = load {load_type}, ptr {ptr}{comment}")

        elif instr.opcode == IROpcode.ADD_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = add i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.SUB_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = sub i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.MUL_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = mul i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.DIV_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = sdiv i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.MOD_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = srem i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.ADD_F:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = fadd double {left}, {right}{comment}")

        elif instr.opcode == IROpcode.SUB_F:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = fsub double {left}, {right}{comment}")

        elif instr.opcode == IROpcode.MUL_F:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = fmul double {left}, {right}{comment}")

        elif instr.opcode == IROpcode.DIV_F:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = fdiv double {left}, {right}{comment}")

        elif instr.opcode == IROpcode.EQ_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp eq i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.NE_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp ne i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.LT_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp slt i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.GT_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp sgt i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.LE_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp sle i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.GE_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                icmp = self._new_temp()
                self._emit_line(f"  {icmp} = icmp sge i32 {left}, {right}{comment}")
                self._emit_line(f"  {dest} = zext i1 {icmp} to i32{comment}")

        elif instr.opcode == IROpcode.AND_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = and i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.OR_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = or i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.XOR_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = xor i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.SHL:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = shl i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.SHR:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._allocate_temp(instr.dest)
                left = self._get_operand_value(instr.operands[0])
                right = self._get_operand_value(instr.operands[1])
                self._emit_line(f"  {dest} = ashr i32 {left}, {right}{comment}")

        elif instr.opcode == IROpcode.NEG:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                op = self._get_operand_value(instr.operands[0])
                self._emit_line(f"  {dest} = sub i32 0, {op}{comment}")

        elif instr.opcode == IROpcode.NOT_I:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                op = self._get_operand_value(instr.operands[0])
                self._emit_line(f"  {dest} = xor i32 {op}, -1{comment}")

        elif instr.opcode == IROpcode.COPY:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                op = self._get_operand_value(instr.operands[0])
                op_type = self._ir_type_to_llvm(instr.operands[0].value_type)
                self._emit_line(f"  {dest} = bitcast {op_type} {op} to {self._ir_type_to_llvm(instr.dest.value_type)}{comment}")

        elif instr.opcode == IROpcode.INT_TO_FLOAT:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                op = self._get_operand_value(instr.operands[0])
                self._emit_line(f"  {dest} = sitofp i32 {op} to double{comment}")

        elif instr.opcode == IROpcode.FLOAT_TO_INT:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                op = self._get_operand_value(instr.operands[0])
                self._emit_line(f"  {dest} = fptosi double {op} to i32{comment}")

        elif instr.opcode == IROpcode.PHI:
            if instr.dest and instr.operands:
                dest = self._allocate_temp(instr.dest)
                incomings = []
                for i in range(0, len(instr.operands), 2):
                    if i + 1 < len(instr.operands):
                        op = self._get_operand_value(instr.operands[i])
                        label = instr.operands[i + 1].name if instr.operands[i + 1].name.startswith("%") else f"%{instr.operands[i + 1].name}"
                        incomings.append(f"[{op}, {label}]")
                phi_type = self._ir_type_to_llvm(instr.dest.value_type)
                self._emit_line(f"  {dest} = phi {phi_type} {', '.join(incomings)}{comment}")

        elif instr.opcode == IROpcode.COMMENT:
            self._emit_line(f"  ; {instr.comment}")

        elif instr.opcode == IROpcode.NOP:
            pass

        elif instr.opcode == IROpcode.MATMUL:
            self._emit_line(f"  ; matmul (not implemented in LLVM IR){comment}")

        elif instr.opcode == IROpcode.RELU:
            self._emit_line(f"  ; relu (not implemented in LLVM IR){comment}")

        else:
            # 通用处理
            ops = ", ".join(self._get_operand_value(op) for op in instr.operands)
            if instr.dest:
                dest = self._allocate_temp(instr.dest)
                self._emit_line(f"  ; {dest} = {instr.opcode.name.lower()}({ops}){comment}")
            else:
                self._emit_line(f"  ; {instr.opcode.name.lower()}({ops}){comment}")

    def _get_operand_value(self, op: IRValue) -> str:
        """获取操作数的 LLVM 值表示"""
        if op.is_constant:
            if op.value_type == IRValueType.FLOAT64:
                # 浮点常量需要特殊格式
                val = float(op.value) if op.value else 0.0
                return f"0x{val.hex()}" if hasattr(val, 'hex') else str(val)
            elif op.value_type == IRValueType.INT1:
                return "1" if op.value else "0"
            elif op.value_type == IRValueType.STRING:
                return f"@\"{op.value}\""
            return str(op.value) if op.value is not None else "0"
        else:
            if op.name.startswith("%"):
                return op.name
            return f"%{op.name.lstrip('%')}"

    def _allocate_temp(self, value: IRValue) -> str:
        """为值分配 LLVM 临时变量"""
        if value.name.startswith("%"):
            return value.name
        name = f"%{value.name.lstrip('%')}"
        self._named_values[value.name] = name
        return name

    def _emit_line(self, line: str = "") -> None:
        """输出一行"""
        self._output.append(line)