"""
AI 编译器工具链 - x86 汇编生成器
"""

from __future__ import annotations

from typing import Optional, Any

from src.middle.ir import (
    IRModule, IRFunction, IRInstruction, IRValue, IRValueType, BasicBlock, IROpcode,
)
from src.utils.errors import CodeGenError, ErrorReporter


class X86Register:
    """x86 寄存器"""

    def __init__(self, name: str, size: int = 32):
        self.name = name
        self.size = size
        self.in_use: bool = False
        self.value: Optional[str] = None

    def __repr__(self) -> str:
        return self.name


class X86RegisterAllocator:
    """x86 寄存器分配器（简化实现）"""

    def __init__(self):
        self.registers: list[X86Register] = [
            X86Register("eax", 32), X86Register("ebx", 32),
            X86Register("ecx", 32), X86Register("edx", 32),
            X86Register("esi", 32), X86Register("edi", 32),
        ]
        self._mapped: dict[str, str] = {}
        self._spill_slot: int = 0
        self._spill_map: dict[str, int] = {}

    def allocate(self, var_name: str) -> str:
        """分配寄存器"""
        if var_name in self._mapped:
            return self._mapped[var_name]

        for reg in self.registers:
            if not reg.in_use:
                reg.in_use = True
                self._mapped[var_name] = reg.name
                return reg.name

        # 溢出到栈
        self._spill_slot += 4
        self._spill_map[var_name] = self._spill_slot
        return f"[ebp-{self._spill_slot}]"

    def free(self, var_name: str) -> None:
        """释放寄存器"""
        if var_name in self._mapped:
            reg_name = self._mapped.pop(var_name)
            for reg in self.registers:
                if reg.name == reg_name:
                    reg.in_use = False
                    break

    def get_spill_offset(self, var_name: str) -> int:
        """获取溢出偏移"""
        return self._spill_map.get(var_name, 0)

    def reset(self) -> None:
        """重置分配器"""
        self._mapped.clear()
        self._spill_map.clear()
        self._spill_slot = 0
        for reg in self.registers:
            reg.in_use = False


class X86Generator:
    """x86 汇编代码生成器"""

    def __init__(self, error_reporter: Optional[ErrorReporter] = None):
        self.error_reporter: ErrorReporter = error_reporter or ErrorReporter()
        self._output: list[str] = []
        self._reg_alloc: X86RegisterAllocator = X86RegisterAllocator()
        self._label_counter: int = 0
        self._current_function: Optional[str] = None
        self._stack_size: int = 0
        self._string_literals: list[tuple[str, str]] = []

    def generate(self, ir_module: IRModule) -> str:
        """从 IR 生成 x86 汇编"""
        self._output = []
        self._reg_alloc.reset()
        self._string_literals = []

        self._emit_line("; Generated by AI Compiler Toolchain")
        self._emit_line("; Target: x86 (32-bit, AT&T syntax)")
        self._emit_line("")
        self._emit_line(".intel_syntax noprefix")
        self._emit_line("")

        # 数据段
        self._emit_line(".data")
        for name, value in self._string_literals:
            self._emit_line(f"{name}: db \"{value}\", 0")
        self._emit_line("")

        # 文本段
        self._emit_line(".text")
        self._emit_line(".globl _start")
        self._emit_line("")

        # 生成函数
        for func_name, func in ir_module.functions.items():
            self._generate_function(func)

        self._emit_line("")
        # 辅助函数
        self._generate_helpers()

        return "\n".join(self._output)

    def _generate_function(self, func: IRFunction) -> None:
        """生成函数"""
        self._current_function = func.name
        self._stack_size = 0
        self._reg_alloc.reset()

        if func.is_entry or func.name == "main":
            self._emit_line("_start:")
            self._emit_line("main:")
        else:
            self._emit_line(f"{func.name}:")

        # 函数序言
        self._emit_line("    push ebp")
        self._emit_line("    mov ebp, esp")
        self._emit_line(f"    sub esp, {self._stack_size}")

        # 生成基本块
        for block in func.blocks:
            self._emit_line(f"{block.name}:")
            for instr in block.instructions:
                self._generate_instruction(instr)

        # 函数尾声
        self._emit_line("    mov esp, ebp")
        self._emit_line("    pop ebp")
        self._emit_line("    ret")
        self._emit_line("")

    def _generate_instruction(self, instr: IRInstruction) -> None:
        """生成单条指令"""
        if instr.opcode == IROpcode.LABEL:
            return  # 已在基本块级别处理

        comment = f"  ; {instr.comment}" if instr.comment else ""

        if instr.opcode == IROpcode.RETURN or instr.opcode == IROpcode.RET:
            if instr.operands:
                op = instr.operands[0]
                if op.is_constant:
                    self._emit_line(f"    mov eax, {op.value}{comment}")
                else:
                    reg = self._reg_alloc.allocate(op.name)
                    self._emit_line(f"    mov eax, {reg}{comment}")
            self._emit_line("    mov esp, ebp")
            self._emit_line("    pop ebp")
            self._emit_line("    ret")

        elif instr.opcode == IROpcode.GOTO:
            self._emit_line(f"    jmp {instr.label}{comment}")

        elif instr.opcode == IROpcode.IF_GOTO:
            cond = instr.operands[0] if instr.operands else None
            if cond:
                if cond.is_constant:
                    if cond.value:
                        self._emit_line(f"    jmp {instr.label}{comment}")
                else:
                    reg = self._reg_alloc.allocate(cond.name)
                    self._emit_line(f"    cmp {reg}, 0{comment}")
                    self._emit_line(f"    je {instr.label}{comment}")

        elif instr.opcode == IROpcode.CALL:
            func_name = instr.operands[0].name if instr.operands else ""
            args = instr.operands[1:]
            # 压入参数（逆序）
            for arg in reversed(args):
                if arg.is_constant:
                    self._emit_line(f"    push {arg.value}{comment}")
                else:
                    reg = self._reg_alloc.allocate(arg.name)
                    self._emit_line(f"    push {reg}{comment}")
            self._emit_line(f"    call {func_name.lstrip('@')}{comment}")
            # 清理参数
            if args:
                self._emit_line(f"    add esp, {len(args) * 4}")
            if instr.dest:
                self._emit_line(f"    mov {self._reg_alloc.allocate(instr.dest.name)}, eax{comment}")

        elif instr.opcode == IROpcode.ALLOCA:
            if instr.dest:
                offset = self._stack_size
                self._stack_size += 4
                self._emit_line(f"    lea {self._reg_alloc.allocate(instr.dest.name)}, [ebp-{offset}]{comment}")

        elif instr.opcode == IROpcode.STORE:
            if len(instr.operands) >= 2:
                ptr = instr.operands[0]
                val = instr.operands[1]
                if val.is_constant:
                    self._emit_line(f"    mov DWORD PTR [{ptr}], {val.value}{comment}")
                else:
                    reg = self._reg_alloc.allocate(val.name)
                    self._emit_line(f"    mov DWORD PTR [{ptr}], {reg}{comment}")

        elif instr.opcode == IROpcode.LOAD:
            if instr.dest and instr.operands:
                ptr = instr.operands[0]
                dest = self._reg_alloc.allocate(instr.dest.name)
                self._emit_line(f"    mov {dest}, DWORD PTR [{ptr}]{comment}")

        elif instr.opcode == IROpcode.ADD_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    add {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    add {dest}, {self._reg_alloc.allocate(right.name)}{comment}")

        elif instr.opcode == IROpcode.SUB_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    sub {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    sub {dest}, {self._reg_alloc.allocate(right.name)}{comment}")

        elif instr.opcode == IROpcode.MUL_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov eax, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov eax, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    imul eax, {right.value}{comment}")
                else:
                    self._emit_line(f"    imul eax, {self._reg_alloc.allocate(right.name)}{comment}")
                self._emit_line(f"    mov {dest}, eax{comment}")

        elif instr.opcode == IROpcode.DIV_I:
            if instr.dest and len(instr.operands) >= 2:
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov eax, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov eax, {self._reg_alloc.allocate(left.name)}{comment}")
                self._emit_line("    cdq")  # sign extend eax to edx:eax
                if right.is_constant:
                    self._emit_line(f"    idiv {right.value}{comment}")
                else:
                    self._emit_line(f"    idiv {self._reg_alloc.allocate(right.name)}{comment}")
                self._emit_line(f"    mov {self._reg_alloc.allocate(instr.dest.name)}, eax{comment}")

        elif instr.opcode == IROpcode.ADD_F:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    fld QWORD PTR [{left.value}]{comment}")
                else:
                    self._emit_line(f"    fld {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    fadd QWORD PTR [{right.value}]{comment}")
                else:
                    self._emit_line(f"    fadd {self._reg_alloc.allocate(right.name)}{comment}")
                self._emit_line(f"    fstp {dest}{comment}")

        elif instr.opcode == IROpcode.COPY:
            if instr.dest and instr.operands:
                src = instr.operands[0]
                dest = self._reg_alloc.allocate(instr.dest.name)
                if src.is_constant:
                    self._emit_line(f"    mov {dest}, {src.value}{comment}")
                else:
                    src_reg = self._reg_alloc.allocate(src.name)
                    self._emit_line(f"    mov {dest}, {src_reg}{comment}")

        elif instr.opcode == IROpcode.EQ_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    cmp {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    cmp {dest}, {self._reg_alloc.allocate(right.name)}{comment}")
                self._emit_line(f"    sete al{comment}")
                self._emit_line(f"    movzx {dest}, al{comment}")

        elif instr.opcode == IROpcode.LT_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    cmp {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    cmp {dest}, {self._reg_alloc.allocate(right.name)}{comment}")
                self._emit_line(f"    setl al{comment}")
                self._emit_line(f"    movzx {dest}, al{comment}")

        elif instr.opcode == IROpcode.AND_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    and {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    and {dest}, {self._reg_alloc.allocate(right.name)}{comment}")

        elif instr.opcode == IROpcode.OR_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    or {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    or {dest}, {self._reg_alloc.allocate(right.name)}{comment}")

        elif instr.opcode == IROpcode.XOR_I:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    xor {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    xor {dest}, {self._reg_alloc.allocate(right.name)}{comment}")

        elif instr.opcode == IROpcode.SHL:
            if instr.dest and len(instr.operands) >= 2:
                dest = self._reg_alloc.allocate(instr.dest.name)
                left, right = instr.operands[0], instr.operands[1]
                if left.is_constant:
                    self._emit_line(f"    mov {dest}, {left.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(left.name)}{comment}")
                if right.is_constant:
                    self._emit_line(f"    shl {dest}, {right.value}{comment}")
                else:
                    self._emit_line(f"    mov ecx, {self._reg_alloc.allocate(right.name)}{comment}")
                    self._emit_line(f"    shl {dest}, cl{comment}")

        elif instr.opcode == IROpcode.NEG:
            if instr.dest and instr.operands:
                dest = self._reg_alloc.allocate(instr.dest.name)
                op = instr.operands[0]
                if op.is_constant:
                    self._emit_line(f"    mov {dest}, {-op.value}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(op.name)}{comment}")
                    self._emit_line(f"    neg {dest}{comment}")

        elif instr.opcode == IROpcode.NOT_I:
            if instr.dest and instr.operands:
                dest = self._reg_alloc.allocate(instr.dest.name)
                op = instr.operands[0]
                if op.is_constant:
                    self._emit_line(f"    mov {dest}, {~op.value & 0xFFFFFFFF}{comment}")
                else:
                    self._emit_line(f"    mov {dest}, {self._reg_alloc.allocate(op.name)}{comment}")
                    self._emit_line(f"    not {dest}{comment}")

        elif instr.opcode == IROpcode.COMMENT:
            self._emit_line(f"    ; {instr.comment}")

        elif instr.opcode == IROpcode.NOP:
            self._emit_line("    nop")

        else:
            # 通用处理
            if instr.dest:
                ops = ", ".join(str(op) for op in instr.operands)
                self._emit_line(f"    ; {instr.dest} = {instr.opcode.name.lower()}({ops}){comment}")
            else:
                ops = ", ".join(str(op) for op in instr.operands)
                self._emit_line(f"    ; {instr.opcode.name.lower()}({ops}){comment}")

    def _emit_line(self, line: str = "") -> None:
        """输出一行"""
        self._output.append(line)

    def _generate_helpers(self) -> None:
        """生成辅助函数"""
        self._emit_line("; Helper functions")
        self._emit_line("")
        self._emit_line("print_int:")
        self._emit_line("    push ebp")
        self._emit_line("    mov ebp, esp")
        self._emit_line("    push eax")
        self._emit_line("    push ebx")
        self._emit_line("    push ecx")
        self._emit_line("    push edx")
        self._emit_line("    ; Convert integer to string and print")
        self._emit_line("    mov eax, [ebp+8]")
        self._emit_line("    ; ... (simplified)")
        self._emit_line("    pop edx")
        self._emit_line("    pop ecx")
        self._emit_line("    pop ebx")
        self._emit_line("    pop eax")
        self._emit_line("    pop ebp")
        self._emit_line("    ret")
        self._emit_line("")

    def _new_label(self, prefix: str = "L") -> str:
        self._label_counter += 1
        return f"{prefix}{self._label_counter}"