# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# Development dependencies
group :development do
  gem 'rake', '~> 13.0'
  gem 'yard', '~> 0.9'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-performance', '~> 1.17'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'solargraph', '~> 0.50'
end

# Test dependencies
group :test do
  gem 'rspec', '~> 3.12'
  gem 'rspec-core', '~> 3.12'
  gem 'rspec-expectations', '~> 3.12'
  gem 'rspec-mocks', '~> 3.12'
  gem 'rspec-support', '~> 3.12'
  gem 'timecop', '~> 0.9'
  gem 'webmock', '~> 3.19'
  gem 'simplecov', '~> 0.22'
  gem 'simplecov-json', '~> 0.2'
end

# Optional dependencies
group :optional do
  gem 'concurrent-ruby', '~> 1.2'
end