/*
 * AinosOS - boot/idt.c
 * Interrupt Descriptor Table initialization
 */

#include <types.h>
#include <macros.h>
#include <arch/x86_64/registers.h>

/* IDT entry structure (64-bit mode) */
struct PACKED idt_entry {
    uint16_t offset_low;     /* Low 16 bits of handler address */
    uint16_t selector;       /* Code segment selector */
    uint8_t  ist;            /* Interrupt Stack Table index (bits 0-2) */
    uint8_t  type_attr;      /* Gate type and attributes */
    uint16_t offset_mid;     /* Middle 16 bits of handler address */
    uint32_t offset_high;    /* High 32 bits of handler address */
    uint32_t reserved;       /* Reserved, must be 0 */
};

/* IDT pointer */
struct PACKED idtr {
    uint16_t limit;
    uint64_t base;
};

/* Interrupt gate types */
#define IDT_TYPE_INTERRUPT      0x0E  /* 64-bit interrupt gate */
#define IDT_TYPE_TRAP           0x0F  /* 64-bit trap gate */
#define IDT_TYPE_TASK           0x05  /* 32-bit task gate */

/* IDT attributes */
#define IDT_PRESENT             (1 << 7)
#define IDT_DPL0                (0 << 5)
#define IDT_DPL1                (1 << 5)
#define IDT_DPL2                (2 << 5)
#define IDT_DPL3                (3 << 5)

/* Interrupt numbers */
#define INT_DIVIDE_ERROR        0
#define INT_DEBUG               1
#define INT_NMI                 2
#define INT_BREAKPOINT          3
#define INT_OVERFLOW            4
#define INT_BOUND_RANGE         5
#define INT_INVALID_OPCODE      6
#define INT_DEVICE_NOT_AVAIL    7
#define INT_DOUBLE_FAULT        8
#define INT_COPROC_SEGMENT      9
#define INT_INVALID_TSS         10
#define INT_SEGMENT_NOT_PRESENT 11
#define INT_STACK_FAULT         12
#define INT_GP_FAULT            13
#define INT_PAGE_FAULT          14
#define INT_RESERVED            15
#define INT_X87_FP              16
#define INT_ALIGNMENT_CHECK     17
#define INT_MACHINE_CHECK       18
#define INT_SIMD_FP             19
#define INT_VIRT                20
#define INT_CONTROL_PROT        21
#define INT_HYPERVISOR          28
#define INT_VMM                 29
#define INT_SECURITY            30

/* IRQ offsets (PIC remapped) */
#define INT_IRQ0                32
#define INT_IRQ1                33
#define INT_IRQ2                34
#define INT_IRQ3                35
#define INT_IRQ4                36
#define INT_IRQ5                37
#define INT_IRQ6                38
#define INT_IRQ7                39
#define INT_IRQ8                40
#define INT_IRQ9                41
#define INT_IRQ10               42
#define INT_IRQ11               43
#define INT_IRQ12               44
#define INT_IRQ13               45
#define INT_IRQ14               46
#define INT_IRQ15               47

/* User-accessible interrupt vectors (for syscalls) */
#define INT_SYSCALL             0x80
#define INT_SYSCALL_64          0x81

/* Spurious interrupt vector */
#define INT_SPURIOUS            0xFF

/* Number of IDT entries */
#define IDT_ENTRIES             256

/* IDT table */
static struct idt_entry idt[IDT_ENTRIES] ALIGNED(16);

/* Interrupt handler table */
typedef void (*interrupt_handler_t)(uint64_t vector, uint64_t error_code, uint64_t *regs);
static interrupt_handler_t interrupt_handlers[IDT_ENTRIES];

/* Forward declarations of assembly stubs */
extern void isr_common_stub(void);
extern void irq_common_stub(void);

/* External ISR entry points (generated by macros in assembly) */
extern void isr_0(void);   extern void isr_1(void);
extern void isr_2(void);   extern void isr_3(void);
extern void isr_4(void);   extern void isr_5(void);
extern void isr_6(void);   extern void isr_7(void);
extern void isr_8(void);   extern void isr_9(void);
extern void isr_10(void);  extern void isr_11(void);
extern void isr_12(void);  extern void isr_13(void);
extern void isr_14(void);  extern void isr_15(void);
extern void isr_16(void);  extern void isr_17(void);
extern void isr_18(void);  extern void isr_19(void);
extern void isr_20(void);  extern void isr_21(void);
extern void isr_22(void);  extern void isr_23(void);
extern void isr_24(void);  extern void isr_25(void);
extern void isr_26(void);  extern void isr_27(void);
extern void isr_28(void);  extern void isr_29(void);
extern void isr_30(void);  extern void isr_31(void);

/* External IRQ stubs */
extern void irq_0(void);   extern void irq_1(void);
extern void irq_2(void);   extern void irq_3(void);
extern void irq_4(void);   extern void irq_5(void);
extern void irq_6(void);   extern void irq_7(void);
extern void irq_8(void);   extern void irq_9(void);
extern void irq_10(void);  extern void irq_11(void);
extern void irq_12(void);  extern void irq_13(void);
extern void irq_14(void);  extern void irq_15(void);

/*
 * Set an IDT entry
 */
static void idt_set_entry(int index, uint64_t handler, uint16_t selector,
                          uint8_t ist, uint8_t type, uint8_t dpl) {
    idt[index].offset_low   = handler & 0xFFFF;
    idt[index].selector     = selector;
    idt[index].ist          = ist & 0x07;
    idt[index].type_attr    = IDT_PRESENT | (dpl << 5) | type;
    idt[index].offset_mid   = (handler >> 16) & 0xFFFF;
    idt[index].offset_high  = (handler >> 32) & 0xFFFFFFFF;
    idt[index].reserved     = 0;
}

/*
 * Initialize the IDT with default handlers
 */
void idt_init(void) {
    /* Clear the IDT */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        *(uint64_t*)&idt[i] = 0;
        *(uint64_t*)((uint8_t*)&idt[i] + 8) = 0;
        interrupt_handlers[i] = NULL;
    }

    /* Install ISR handlers for exceptions 0-31 */
    void *isr_stubs[] = { &isr_0,  &isr_1,  &isr_2,  &isr_3,
                          &isr_4,  &isr_5,  &isr_6,  &isr_7,
                          &isr_8,  &isr_9,  &isr_10, &isr_11,
                          &isr_12, &isr_13, &isr_14, &isr_15,
                          &isr_16, &isr_17, &isr_18, &isr_19,
                          &isr_20, &isr_21, &isr_22, &isr_23,
                          &isr_24, &isr_25, &isr_26, &isr_27,
                          &isr_28, &isr_29, &isr_30, &isr_31 };

    for (int i = 0; i < 32; i++) {
        /* Exceptions 8 and 10-14 have error codes */
        /* Interrupt gate, DPL=0 */
        idt_set_entry(i, (uint64_t)isr_stubs[i], 0x08, 0, IDT_TYPE_INTERRUPT, 0);
    }

    /* Install IRQ handlers for vectors 32-47 */
    void *irq_stubs[] = { &irq_0,  &irq_1,  &irq_2,  &irq_3,
                          &irq_4,  &irq_5,  &irq_6,  &irq_7,
                          &irq_8,  &irq_9,  &irq_10, &irq_11,
                          &irq_12, &irq_13, &irq_14, &irq_15 };

    for (int i = 0; i < 16; i++) {
        idt_set_entry(INT_IRQ0 + i, (uint64_t)irq_stubs[i], 0x08, 0, IDT_TYPE_INTERRUPT, 0);
    }

    /* Set up special interrupt gates */
    /* Breakpoint (int3) - user accessible */
    idt_set_entry(INT_BREAKPOINT, (uint64_t)isr_3, 0x08, 0, IDT_TYPE_TRAP, 3);

    /* Debug exception - user accessible */
    idt_set_entry(INT_DEBUG, (uint64_t)isr_1, 0x08, 0, IDT_TYPE_TRAP, 3);

    /* Syscall handler (legacy) */
    idt_set_entry(INT_SYSCALL, (uint64_t)isr_common_stub, 0x08, 0, IDT_TYPE_INTERRUPT, 3);

    /* Double fault with IST stack */
    idt_set_entry(INT_DOUBLE_FAULT, (uint64_t)isr_8, 0x08, 1, IDT_TYPE_INTERRUPT, 0);

    /* NMI */
    idt_set_entry(INT_NMI, (uint64_t)isr_2, 0x08, 2, IDT_TYPE_INTERRUPT, 0);

    /* Load the IDT */
    struct idtr idtr_struct;
    idtr_struct.limit = sizeof(idt) - 1;
    idtr_struct.base  = (uint64_t)idt;
    lidt(&idtr_struct);
}

/*
 * Register an interrupt handler
 */
void idt_register_handler(int vector, interrupt_handler_t handler) {
    if (vector >= 0 && vector < IDT_ENTRIES) {
        interrupt_handlers[vector] = handler;
    }
}

/*
 * Get the registered handler for a vector
 */
interrupt_handler_t idt_get_handler(int vector) {
    if (vector >= 0 && vector < IDT_ENTRIES) {
        return interrupt_handlers[vector];
    }
    return NULL;
}

/*
 * Common ISR handler (called from assembly)
 * This is the C-level handler for all exceptions
 */
void isr_handler(uint64_t vector, uint64_t error_code, uint64_t *regs) {
    /* Call registered handler if present */
    if (interrupt_handlers[vector] != NULL) {
        interrupt_handlers[vector](vector, error_code, regs);
        return;
    }

    /* Default handler: print exception info and halt */
    boot_printf("\n!!! EXCEPTION: Vector 0x%llX, Error Code: 0x%llX !!!\n",
                vector, error_code);
    boot_printf("    RAX: 0x%016llX  RBX: 0x%016llX\n", regs[0], regs[1]);
    boot_printf("    RCX: 0x%016llX  RDX: 0x%016llX\n", regs[2], regs[3]);
    boot_printf("    RSI: 0x%016llX  RDI: 0x%016llX\n", regs[4], regs[5]);
    boot_printf("    RBP: 0x%016llX  RSP: 0x%016llX\n", regs[6], regs[7]);
    boot_printf("    R8:  0x%016llX  R9:  0x%016llX\n", regs[8], regs[9]);
    boot_printf("    R10: 0x%016llX  R11: 0x%016llX\n", regs[10], regs[11]);
    boot_printf("    R12: 0x%016llX  R13: 0x%016llX\n", regs[12], regs[13]);
    boot_printf("    R14: 0x%016llX  R15: 0x%016llX\n", regs[14], regs[15]);
    boot_printf("    RIP: 0x%016llX  CS:  0x%016llX\n", regs[16], regs[17]);
    boot_printf("    RFLAGS: 0x%016llX  SS: 0x%016llX\n", regs[18], regs[19]);

    const char *exception_names[] = {
        "Divide Error", "Debug", "NMI", "Breakpoint",
        "Overflow", "BOUND Range", "Invalid Opcode", "Device Not Available",
        "Double Fault", "Coprocessor Segment", "Invalid TSS", "Segment Not Present",
        "Stack-Segment Fault", "General Protection", "Page Fault", "Reserved",
        "x87 FPU Error", "Alignment Check", "Machine Check", "SIMD FP Exception",
        "Virtualization", "Control Protection", "", "", "", "", "",
        "", "", "Hypervisor Injection", "VMM Communication", "Security"
    };

    if (vector < 32) {
        boot_printf("    Exception: %s\n", exception_names[vector]);
    }

    if (vector == 14) {
        /* Page fault - show additional info */
        uint64_t cr2 = read_cr2();
        boot_printf("    CR2 (Fault Address): 0x%016llX\n", cr2);
        boot_printf("    Page Fault Error Code:\n");
        boot_printf("      %s\n", (error_code & 1) ? "  Protection violation" : "  Non-present page");
        boot_printf("      %s\n", (error_code & 2) ? "  Write access" : "  Read access");
        boot_printf("      %s\n", (error_code & 4) ? "  User mode" : "  Supervisor mode");
        boot_printf("      %s\n", (error_code & 8) ? "  Reserved bit violation" : "");
        boot_printf("      %s\n", (error_code & 16) ? "  Instruction fetch" : "");
    }

    /* Halt the system */
    boot_panic("Unhandled exception");
}

/*
 * Common IRQ handler (called from assembly)
 * Handles hardware interrupt requests, sends EOI, calls registered handler
 */
void irq_handler(uint64_t vector, uint64_t *regs) {
    uint64_t irq = vector - INT_IRQ0;

    /* Call registered handler if present */
    if (interrupt_handlers[vector] != NULL) {
        interrupt_handlers[vector](vector, 0, regs);
    }

    /* Send EOI to PIC if we're using legacy PIC mode */
    if (irq >= 8) {
        outb(0xA0, 0x20);  /* Slave PIC */
    }
    outb(0x20, 0x20);      /* Master PIC */

    /* In x2APIC mode, EOI is done via MSR */
    /* For now, we handle both */
}

/*
 * Initialize the PIC (Legacy 8259A)
 * This is used before APIC is fully initialized
 */
void pic_init(void) {
    /* Remap IRQs to vectors 32-47 */
    /* ICW1: Initialize */
    outb(0x20, 0x11);  /* Master */
    outb(0xA0, 0x11);  /* Slave */

    /* ICW2: Vector offsets */
    outb(0x21, 32);    /* Master: IRQ0-7 -> vectors 32-39 */
    outb(0xA1, 40);    /* Slave: IRQ8-15 -> vectors 40-47 */

    /* ICW3: Cascading */
    outb(0x21, 0x04);  /* Master: slave at IRQ2 */
    outb(0xA1, 0x02);  /* Slave: cascade identity */

    /* ICW4: Environment info */
    outb(0x21, 0x01);  /* 8086 mode */
    outb(0xA1, 0x01);

    /* Mask all interrupts */
    outb(0x21, 0xFF);
    outb(0xA1, 0xFF);
}

/*
 * Mask an IRQ line on the PIC
 */
void pic_mask_irq(int irq) {
    if (irq < 8) {
        outb(0x21, inb(0x21) | (1 << irq));
    } else {
        outb(0xA1, inb(0xA1) | (1 << (irq - 8)));
    }
}

/*
 * Unmask an IRQ line on the PIC
 */
void pic_unmask_irq(int irq) {
    if (irq < 8) {
        outb(0x21, inb(0x21) & ~(1 << irq));
    } else {
        outb(0xA1, inb(0xA1) & ~(1 << (irq - 8)));
    }
}

/*
 * Disable the PIC (used when switching to APIC mode)
 */
void pic_disable(void) {
    outb(0xA1, 0xFF);
    outb(0x21, 0xFF);
}